[project]
name = "python-books"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "reflex>=0.7.1",
    "wikipedia-api>=0.8.1",
]
