"""empty message

Revision ID: 92016b5d5c46
Revises: c500c399ba9f
Create Date: 2025-03-06 09:33:07.782466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '92016b5d5c46'
down_revision: Union[str, None] = 'c500c399ba9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('num_times_read',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('num_times_read',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
